@startuml
skinparam classAttributeIconSize 0

Abstract Person{
- Navn: String
- Efternavn: String
}

Class AfleveringsController{
hentAflevering()
uploadAflevering(String )
retAflevering()
}


Abstract Ansat{
-Løn
}
class Lærer{

}
class Hjælpelærer{
- Løn : int
}
class Aflevering{
Afleveringsbeskrivelse: String
tidsfrist()
}
class Studerende{
- Studienummer: String
}
class Kursus{
Kursusbeskrivelse: String

}
class System{

hentAflevering()

}
Person <|-- Studerende : uploadsAflevering
Ansat <|-- Lærer : opretterAflevering
Ansat <|-- Hjælpelærer :downloadsAflevering/uploadsFeedback
Ansat --|> Person
Kursus"1" --> "*"Aflevering :indeholder
System"1" --> "1..*"Kursus: indeholder
Person "1" --> "1" System
AfleveringsController --> Aflevering



@enduml