@startuml
skinparam classAttributeIconSize 0
class BrugerController{
getPersonOplysninger()
isPesonAnsat(ID): boolean
isPersonHjælpelærer(ID): boolean
isPersonTeacher(ID): boolean
}
class Bruger{
-Navn: String
-Efternavn: String
-ID: String
}

class AfleveringsController{
hentAflevering()
uploadAflevering(String )
retAflevering()
}

class Aflevering{
Afleveringsbeskrivelse: String
tidsfrist()

}
class System{

getKursusOptions(ID)

}
class Kursus{
KursusNr: int
KursusNavn: int

}
BrugerController <-- Bruger
Kursus"1" --> "1"AfleveringsController :indeholder
System"1" --> "1..*"Kursus: indeholder
BrugerController "1" --> "1" System
AfleveringsController --> Aflevering



@enduml