@startuml
'https://plantuml.com/class-diagram


Class Lærer
Class Hjælpelærer
Class Studerende
Class Ansat
Class Aflevering{
AfleveringsDato
}
Class Kursus
Class Person

Lærer --|> Ansat
Studerende  --|> Person
Hjælpelærer --|> Ansat
Ansat --|> Person
Kursus -- Aflevering
Person -- Kursus

@enduml